### ISSUE TITLE
Waiting act  calls returns some warnings

### ISSUE THREAD

**Issue by krvajal** [threepointone/react-act-examples#7]
I wrote something like this on my tests
```
await act(async () => {
        fireEvent.click(getByText('Register Visit'));
        await flushPromises();
    });

```
Similar to what is shown here

https://github.com/threepointone/react-act-examples/blob/master/act-examples.test.js#L95

but I am getting these warnings
```
Warning: The callback passed to ReactTestUtils.act(...) function must not return anything.

    It looks like you wrote ReactTestUtils.act(async () => ...), or returned a Promise from the callback passed to it. Putting asynchronous logic inside ReactTestUtils.act(...) is not supported.


  console.error node_modules/react-dom/cjs/react-dom-test-utils.development.js:100
    Warning: Do not await the result of calling ReactTestUtils.act(...), it is not a Promise.
```

The version of React that I am using is 16.8.6

**Comment by threepointone** [comment]
async act only works in the 16.9 alpha. we haven't released it fully yet.

**Comment by krvajal** [comment]
Yeah, just realized that. Any workarounds?

**Comment by krvajal** [comment]
In my case, I am using redux-saga, which is doing some async work and updating the component.

**Comment by threepointone** [comment]
not sure what you're asking? you could wait for 16.9, or silence warnings.

**Comment by krvajal** [comment]
Well, I just want the component to update properly.
I am using this and it seems to work
```
act(() => {
        fireEvent.click(getByText('Register Visit'));
    });

    await flushPromises();

    act(() => {
        // force updates
    });
```
 but not sure if the second act call is doing anything.

**Comment by danielkcz** [comment]
> not sure what you're asking? you could wait for 16.9, or silence warnings.

Or use 16.9-alpha.0 ;) We have it already in production, no issues with it so far.

**Comment by threepointone** [comment]
I would *NOT* recommend using the alpha in production. It's likely we might ship breaking changes before release.

**Comment by danielkcz** [comment]
@threepointone That's fair warning, but we have happily ignored the same one with 16.7 alpha and went with hooks to production😄 We don't really mind some refactoring. It's a low cost for a better DX.
